    PROGRAM COKRIGING

    INTEGER::I,J,K,P,M_SEARCH_RADIUS,COUNTER
    INTEGER::N_Z,N_KNOWN,DUMMY_T,DUMMY_L
    INTEGER::N_KNOWN_T
    INTEGER::N_KNOWN_L
    REAL::SIGMA_SQUARE,L,SUM_M,SUM_B,SUM_LAMBDA,SUM_MU
    REAL::SIGMA_SQUARE_T,L_T
    REAL::SIGMA_SQUARE_L,L_L
    REAL::SIGMA_SQUARE_T_L,L_T_L
    REAL::SEARCH_RADIUS_M,SEARCH_RADIUS_N,FACTOR
    REAL::I_X_T,I_Y_T,I_X_L,I_Y_L
    REAL::MEAN_T,T_KRIGE_MEAN,L_KRIGE_MEAN
    REAL,ALLOCATABLE,DIMENSION(:,:)::A,A1,A2,A3,A4
    REAL,ALLOCATABLE,DIMENSION(:)::B,MU,LAMBDA
    REAL,ALLOCATABLE,DIMENSION(:)::X_Z,Y_Z,T_Z
    REAL,ALLOCATABLE,DIMENSION(:)::X_KNOWN,Y_KNOWN
    REAL,ALLOCATABLE,DIMENSION(:)::X_KNOWN_T,Y_KNOWN_T,T
    REAL,ALLOCATABLE,DIMENSION(:)::X_KNOWN_L,Y_KNOWN_L,L_B
!    INTEGER,ALLOCATABLE,DIMENSION(:)::M_SEARCH_RADIUS
    REAL::X_KRIGE_T(10000),Y_KRIGE_T(10000),T_KRIGE(10000)
    REAL::X_KRIGE_L(10000),Y_KRIGE_L(10000),L_B_KRIGE(10000)
    REAL DISTANCE(1000),T_TRND(1000),B_TRND(1000)
    !N_Z:NUMBER OF TARGETS AT WHICH ESTIMATED VALUE IS NEEDED
    !SIGMA_SQUARE,L:PARAMTERS OF GAUSSIAN VARIOGRAM USED
    !SIGMA_SQUARE_T,L_T:PARAMTERS OF GAUSSIAN VARIOGRAM USED FOR TRANSMISSIVITY
    !SIGMA_SQUARE_L,L_L:PARAMTERS OF GAUSSIAN VARIOGRAM USED FOR LITHOLOGICAL DATA
    !SIGMA_SQUARE_T_L,L_T_L:PARAMTERS OF GAUSSIAN CROSS VARIOGRAM USED FOR TRANSMISSIVITY AND LITHOLOGICAL DATA
    !SEARCH_RADIUS: RADIUS IN WHICH POINTS LYING PARTICIPATE IN KRIGING
    !M_SEARCH_RADIUS:NUMBER OF T POINTS LYING INSIDE SEARCH RADIUS AND THUS PARTICIPATING IN KRIGING
    !N_SEARCH_RADIUS:NUMBER OF L POINTS LYING INSIDE SEARCH RADIUS AND THUS PARTICIPATING IN KRIGING
    !SUM_B:SUM OF WEIGHTS.SHOULD BE EQUAL TO 1

    OPEN(UNIT=100,FILE='VARIOGRAM_PARAMETERS_T.TXT',STATUS='OLD')
    READ (100,*) SIGMA_SQUARE_T,L_T
    CLOSE (100)

    OPEN(UNIT=101,FILE='VARIOGRAM_PARAMETERS_L.TXT',STATUS='OLD')
    READ (101,*) SIGMA_SQUARE_L,L_L
    CLOSE (101)

    OPEN(UNIT=102,FILE='VARIOGRAM_PARAMETERS_T_L.TXT',STATUS='OLD')
    READ (102,*) SIGMA_SQUARE_T_L,L_T_L
    CLOSE (102)

    WRITE (*,*) SIGMA_SQUARE_T,L_T
    WRITE (*,*) SIGMA_SQUARE_L,L_L
    WRITE (*,*) SIGMA_SQUARE_T_L,L_T_L

    MEAN_T=0.0
    OPEN(UNIT=200,FILE='KNOWN_POINTS_T.TXT',STATUS='OLD')
    READ (200,*) N_KNOWN_T
    ALLOCATE (X_KNOWN_T(N_KNOWN_T),Y_KNOWN_T(N_KNOWN_T),T(N_KNOWN_T))
    DO I=1,N_KNOWN_T
    READ (200,*) X_KNOWN_T(I),Y_KNOWN_T(I),T(I)
    MEAN_T=MEAN_T+T(I)
!    WRITE (*,*) X_KNOWN_T(I),Y_KNOWN_T(I),T(I)
    END DO
    MEAN_T=MEAN_T/N_KNOWN_T
    CLOSE (200)
    WRITE (*,*) MEAN_T


    OPEN(UNIT=201,FILE='KNOWN_POINTS_L.TXT',STATUS='OLD')
    READ (201,*) N_KNOWN_L
    ALLOCATE (X_KNOWN_L(N_KNOWN_L),Y_KNOWN_L(N_KNOWN_L),L_B(N_KNOWN_L))
    DO I=1,N_KNOWN_L
    READ (201,*) X_KNOWN_L(I),Y_KNOWN_L(I),L_B(I)
!    WRITE (*,*) X_KNOWN_L(I),Y_KNOWN_L(I),L_B(I)
    END DO
    CLOSE (201)


    OPEN(UNIT=300,FILE='TARGET_POINTS.TXT',STATUS='OLD')
    READ (300,*) N_Z
    WRITE (*,*) N_Z
    ALLOCATE (X_Z(N_Z),Y_Z(N_Z),T_Z(N_Z))
    DO I=1,N_Z
    READ (300,*) X_Z(I),Y_Z(I)
!    WRITE (*,*) X_Z(I),Y_Z(I)
    END DO
    CLOSE (300)

    OPEN (UNIT=400,FILE='SEARCH_RADIUS.TXT',STATUS='OLD')
    READ (400,*) SEARCH_RADIUS_M,SEARCH_RADIUS_N
!    WRITE (*,*) "SEARCH RADIUS_M=",SEARCH_RADIUS_M,"SEARCH RADIUS_N=",SEARCH_RADIUS_N
    CLOSE (400)


    OPEN (UNIT=500,FILE='TREND_DATA.TXT',STATUS='OLD')
    READ (500,*) I_X_T,I_Y_T,I_X_L,I_Y_L
!    WRITE (*,*) "I_X_T=",I_X_T,"I_Y_T=",I_Y_T,"I_X_L=",I_X_L,"I_Y_L=",I_Y_L
    CLOSE (500)

    COUNTER=0
    OPEN (UNIT=9000,FILE='WEIGHTS.TXT',STATUS='UNKNOWN')
    OPEN (UNIT=9005,FILE='T_KRIGED.TXT',STATUS='UNKNOWN')
    DO K=1,N_Z ! ESTIMATION OF PRIMARY VARIABLE AT UNSAMPLED TARGET POINT(S) STARTS
    T_KRIGE_MEAN=0.0
    L_KRIGE_MEAN=0.0
    WRITE (*,*) K
    SUM_B=0
    T_Z(K)=0.0
    M_SEARCH_RADIUS=0
    DUMMY_T=0
    DO I=1,N_KNOWN_T
    IF (SQRT(((X_Z(K)-X_KNOWN_T(I))**2)+((Y_Z(K)-Y_KNOWN_T(I))**2))<=SEARCH_RADIUS_M) THEN
    DUMMY_T=DUMMY_T+1
    M_SEARCH_RADIUS=M_SEARCH_RADIUS+1
    X_KRIGE_T(DUMMY_T)=X_KNOWN_T(I)
    Y_KRIGE_T(DUMMY_T)=Y_KNOWN_T(I)
    T_KRIGE(DUMMY_T)=T(I)
    T_KRIGE_MEAN=T_KRIGE_MEAN+T(I)
    END IF
    END DO
    T_KRIGE_MEAN=T_KRIGE_MEAN/M_SEARCH_RADIUS

    N_SEARCH_RADIUS=0
    DUMMY_L=0

    DO I=1,N_KNOWN_L
    IF (SQRT(((X_Z(K)-X_KNOWN_L(I))**2)+((Y_Z(K)-Y_KNOWN_L(I))**2))<=SEARCH_RADIUS_N) THEN


    DUMMY_L=DUMMY_L+1
    N_SEARCH_RADIUS=N_SEARCH_RADIUS+1
    DISTANCE(DUMMY_L)=SQRT(((X_Z(K)-X_KNOWN_L(I))**2)+((Y_Z(K)-Y_KNOWN_L(I))**2))
    X_KRIGE_L(DUMMY_L)=X_KNOWN_L(I)
    Y_KRIGE_L(DUMMY_L)=Y_KNOWN_L(I)
    L_B_KRIGE(DUMMY_L)=L_B(I)
    L_KRIGE_MEAN=L_KRIGE_MEAN+L_B(I)
    END IF
    END DO
    L_KRIGE_MEAN=L_KRIGE_MEAN/N_SEARCH_RADIUS


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

   ! 4 CASES OF M AND N


    IF ((M_SEARCH_RADIUS>0).AND.(N_SEARCH_RADIUS>0)) THEN !!!IF CASE 1

    ALLOCATE (A(M_SEARCH_RADIUS+N_SEARCH_RADIUS+2,M_SEARCH_RADIUS+N_SEARCH_RADIUS+2))
    ALLOCATE (A1(M_SEARCH_RADIUS,M_SEARCH_RADIUS))
    ALLOCATE (A2(M_SEARCH_RADIUS,N_SEARCH_RADIUS))
    ALLOCATE (A3(N_SEARCH_RADIUS,M_SEARCH_RADIUS))
    ALLOCATE (A4(N_SEARCH_RADIUS,N_SEARCH_RADIUS))
    ALLOCATE (B(M_SEARCH_RADIUS+N_SEARCH_RADIUS+2))


    DO I=1,M_SEARCH_RADIUS
    DO J=1,M_SEARCH_RADIUS
    A1(I,J)=GAMMA_H_T(X_KRIGE_T(I),Y_KRIGE_T(I),X_KRIGE_T(J),Y_KRIGE_T(J),SIGMA_SQUARE_T,L_T)
    END DO
    END DO

    DO I=1,M_SEARCH_RADIUS
    DO J=1,N_SEARCH_RADIUS
    A2(I,J)=GAMMA_H_T_L(X_KRIGE_L(J),Y_KRIGE_L(J),X_KRIGE_T(I),Y_KRIGE_T(I),SIGMA_SQUARE_T_L,L_T_L)
    END DO
    END DO

    DO I=1,N_SEARCH_RADIUS
    DO J=1,M_SEARCH_RADIUS
    A3(I,J)=GAMMA_H_T_L(X_KRIGE_L(I),Y_KRIGE_L(I),X_KRIGE_T(J),Y_KRIGE_T(J),SIGMA_SQUARE_T_L,L_T_L)
    END DO
    END DO

    DO I=1,N_SEARCH_RADIUS
    DO J=1,N_SEARCH_RADIUS
    A4(I,J)=GAMMA_H_L(X_KRIGE_L(I),Y_KRIGE_L(I),X_KRIGE_L(J),Y_KRIGE_L(J))
    END DO
    END DO

    DO I=1,M_SEARCH_RADIUS
    DO J=1,M_SEARCH_RADIUS
    A(I,J)=A1(I,J)
    END DO
    END DO

    DO I=1,M_SEARCH_RADIUS
    DO J=1,N_SEARCH_RADIUS
    A(I,J+M_SEARCH_RADIUS)=A2(I,J)*T_KRIGE_MEAN/L_KRIGE_MEAN
    END DO
    END DO

    DO I=1,N_SEARCH_RADIUS
    DO J=1,M_SEARCH_RADIUS
    A(I+M_SEARCH_RADIUS,J)=A3(I,J)
    END DO
    END DO

    DO I=1,N_SEARCH_RADIUS
    DO J=1,N_SEARCH_RADIUS
    A(I+M_SEARCH_RADIUS,J+M_SEARCH_RADIUS)=A4(I,J)*T_KRIGE_MEAN/L_KRIGE_MEAN
    END DO
    END DO

    ! SECOND LAST COLUMN
    DO I=1,M_SEARCH_RADIUS
    A(I,N_SEARCH_RADIUS+M_SEARCH_RADIUS+1)=1
    END DO

    DO I=M_SEARCH_RADIUS+1,N_SEARCH_RADIUS+M_SEARCH_RADIUS
    A(I,N_SEARCH_RADIUS+M_SEARCH_RADIUS+1)=0
    END DO

    DO I=N_SEARCH_RADIUS+M_SEARCH_RADIUS+1,N_SEARCH_RADIUS+M_SEARCH_RADIUS+2
    A(I,N_SEARCH_RADIUS+M_SEARCH_RADIUS+1)=0
    END DO

!  LAST COLUMN
    DO I=1,M_SEARCH_RADIUS
    A(I,N_SEARCH_RADIUS+M_SEARCH_RADIUS+2)=0
    END DO

    DO I=M_SEARCH_RADIUS+1,N_SEARCH_RADIUS+M_SEARCH_RADIUS
    A(I,N_SEARCH_RADIUS+M_SEARCH_RADIUS+2)=1
    END DO

    DO I=N_SEARCH_RADIUS+M_SEARCH_RADIUS+1,N_SEARCH_RADIUS+M_SEARCH_RADIUS+2
    A(I,N_SEARCH_RADIUS+M_SEARCH_RADIUS+2)=0
    END DO

! SECOND LAST ROW

    DO J=1,M_SEARCH_RADIUS
    A(N_SEARCH_RADIUS+M_SEARCH_RADIUS+1,J)=1.0
    END DO

    DO J=M_SEARCH_RADIUS+1,N_SEARCH_RADIUS+M_SEARCH_RADIUS+2
    A(N_SEARCH_RADIUS+M_SEARCH_RADIUS+1,J)=0.0
    END DO

    ! LAST ROW

    DO J=1,M_SEARCH_RADIUS
    A(N_SEARCH_RADIUS+M_SEARCH_RADIUS+2,J)=0.0
    END DO

    DO J=M_SEARCH_RADIUS+1,N_SEARCH_RADIUS+M_SEARCH_RADIUS
    A(N_SEARCH_RADIUS+M_SEARCH_RADIUS+2,J)=1.0
    END DO

    DO J=N_SEARCH_RADIUS+M_SEARCH_RADIUS+1,N_SEARCH_RADIUS+M_SEARCH_RADIUS+2
    A(N_SEARCH_RADIUS+M_SEARCH_RADIUS+2,J)=0.0
    END DO

    DO I=1,M_SEARCH_RADIUS
    B(I)=GAMMA_H_T(X_KRIGE_T(I),Y_KRIGE_T(I),X_Z(K),Y_Z(K),SIGMA_SQUARE_T,L_T)
    END DO

    DO I=1,N_SEARCH_RADIUS
    B(I+M_SEARCH_RADIUS)=GAMMA_H_T_L(X_KRIGE_L(I),Y_KRIGE_L(I),X_Z(K),Y_Z(K),SIGMA_SQUARE_T_L,L_T_L)
    END DO

    B(N_SEARCH_RADIUS+M_SEARCH_RADIUS+1)=1.0
    B(N_SEARCH_RADIUS+M_SEARCH_RADIUS+2)=T_KRIGE_MEAN/L_KRIGE_MEAN

    ! SOLVING LINEAR SET OF EQUATIONS USING PIVOTED GAUSS ELIMINATION

    CALL MATINV(A,M_SEARCH_RADIUS+N_SEARCH_RADIUS+2,B,1,DETERM,ID)


    T_Z(K)=0
    DO I=1,M_SEARCH_RADIUS
    T_Z(K)=T_Z(K)+B(I)*T_KRIGE(I)
    SUM_B=SUM_B+B(I)
    END DO
    SUM_B=0
    DO I=1,N_SEARCH_RADIUS
    T_Z(K)=T_Z(K)+B(I+M_SEARCH_RADIUS)*L_B_KRIGE(I)
    SUM_B=SUM_B+B(I+M_SEARCH_RADIUS)
    END DO
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !HALVING ESTIMATE BECAUSE TRANMSSIVITY FROM TRANMISSIVITY DATA AND LITHOLOGICAL DATA DOUBLING ESTIMATE
    T_Z(K)=0.5*T_Z(K)

!    WRITE (*,*) "T_Z(K)=",T_Z(K),"L_B=",L_B(K)

    WRITE (9000,*) "TARGET POINT NUMBER=",K,"ESTIMATED TRANSMISSIVITY",T_Z(K)
    WRITE (9000,*) "M=",M_SEARCH_RADIUS,"N=",N_SEARCH_RADIUS
    WRITE (9000,*) "T_MEAN=",T_KRIGE_MEAN,"L_B_MEAN=",L_KRIGE_MEAN
    WRITE (9000,*) "T_MEAN/L_MEAN=",T_KRIGE_MEAN/L_KRIGE_MEAN
    DO I=1,M_SEARCH_RADIUS
    WRITE (9000,*) "WEIGHTS TRANSMISSIVITIES=",I,B(I),"T_KNOWN",T_KRIGE(I)
    END DO
    DO I=1,N_SEARCH_RADIUS
    WRITE (9000,*) DISTANCE(I),"WEIGHTS SATURATED THICKNESS=",I,B(I+M_SEARCH_RADIUS),"B_KNOWN=",L_B_KRIGE(I)
    END DO

    DEALLOCATE(A,A1,A2,A3,A4,B)


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !CASE 2


    ELSE IF ((M_SEARCH_RADIUS==0).AND.(N_SEARCH_RADIUS>0)) THEN

    ALLOCATE (A(N_SEARCH_RADIUS+1,N_SEARCH_RADIUS+1),A4(N_SEARCH_RADIUS+1,N_SEARCH_RADIUS+1))
    ALLOCATE (B(N_SEARCH_RADIUS+1))


    DO I=1,N_SEARCH_RADIUS
    DO J=1,N_SEARCH_RADIUS
    A4(I,J)=GAMMA_H_L(X_KRIGE_L(I),Y_KRIGE_L(I),X_KRIGE_L(J),Y_KRIGE_L(J))
    END DO
    END DO

    DO I=1,N_SEARCH_RADIUS
    DO J=1,N_SEARCH_RADIUS
    A(I,J)=A4(I,J)*MEAN_T/L_KRIGE_MEAN
    END DO
    END DO

!   LAST COLUMN

    DO I=1,N_SEARCH_RADIUS
    A(I,N_SEARCH_RADIUS+1)=1
    END DO

!   LAST ROW

    DO J=1,N_SEARCH_RADIUS
    A(N_SEARCH_RADIUS+1,J)=1
    END DO

!   CORNER ELEMENT

    A(N_SEARCH_RADIUS+1,N_SEARCH_RADIUS+1)=0

    DO I=1,N_SEARCH_RADIUS
    B(I)=GAMMA_H_T_L(X_KRIGE_L(I),Y_KRIGE_L(I),X_Z(K),Y_Z(K),SIGMA_SQUARE_T_L,L_T_L)
    END DO

    B(N_SEARCH_RADIUS+1)=MEAN_T/L_KRIGE_MEAN

    CALL MATINV(A,N_SEARCH_RADIUS+1,B,1,DETERM,ID)


    DO I=1,N_SEARCH_RADIUS
    T_Z(K)=T_Z(K)+B(I)*L_B_KRIGE(I)
    END DO

!    WRITE (*,*) "T_Z(K)=",T_Z(K),"L_B=",L_B(K)

    WRITE (9000,*) "TARGET POINT NUMBER=",K,"ESTIMATED TRANSMISSIVITY",T_Z(K)
    WRITE (9000,*) "M=",M_SEARCH_RADIUS,"N=",N_SEARCH_RADIUS
    WRITE (9000,*) "T_MEAN=",MEAN_T,"L_B_MEAN=",L_KRIGE_MEAN
    WRITE (9000,*) "T_MEAN/L_MEAN=",MEAN_T/L_KRIGE_MEAN
    DO I=1,M_SEARCH_RADIUS
    WRITE (9000,*) "WEIGHTS TRANSMISSIVITIES=",I,B(I),"T_KNOWN",T_KRIGE(I)
    END DO
    DO I=1,N_SEARCH_RADIUS
    WRITE (9000,*) DISTANCE(I),"WEIGHTS SATURATED THICKNESS=",I,B(I+M_SEARCH_RADIUS),"B_KNOWN=",L_B_KRIGE(I)
    END DO


    DEALLOCATE (A,A4,B)


    ELSE IF (M_SEARCH_RADIUS==0.AND.N_SEARCH_RADIUS==0) THEN
    T_Z(K)=MEAN_T
    END IF

    DO I=1,N_Z
    T_TRND(I)=T_Z(I)+I_X_T*X_Z(I)+I_Y_T*Y_Z(I)
    B_TRND(I)=L_B(I)+I_X_L*X_Z(I)+I_Y_L*Y_Z(I)
    END DO
    WRITE (*,*) "M=",M_SEARCH_RADIUS,"N=",N_SEARCH_RADIUS
    WRITE (9005,*) "X_Z(K)=",X_Z(K),"Y_Z(K)=",Y_Z(K),"L_B(K)=",L_B(K),"T_Z(K)=",T_Z(K), &
    "T_TRND=",T_TRND(K),"B_TRND=",B_TRND(K)
    END DO !END OF K LOOP
    CLOSE (9005)
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!1END CASE 1



    END PROGRAM

    FUNCTION GAMMA_H_T(X_1,Y_1,X_2,Y_2,SIGMA_SQUARE_T,L_T)
    REAL,INTENT(IN)::X_1
    REAL,INTENT(IN)::Y_1
    REAL,INTENT(IN)::X_2
    REAL,INTENT(IN)::Y_2
    REAL,INTENT(IN)::SIGMA_SQUARE_T
    REAL,INTENT(IN)::L_T
    REAL::H
    H=SQRT(((X_1-X_2)**2)+((Y_1-Y_2)**2))
!    GAMMA_H_T=SIGMA_SQUARE_T*(1-EXP(-((H/L_T)**2)))
    GAMMA_H_T=SIGMA_SQUARE_T-SIGMA_SQUARE_T*(1-EXP(-((H/L_T)**2)))
    END FUNCTION


    FUNCTION GAMMA_H_T_L(X_1,Y_1,X_2,Y_2,SIGMA_SQUARE_T_L,L_T_L)
    REAL,INTENT(IN)::X_1
    REAL,INTENT(IN)::Y_1
    REAL,INTENT(IN)::X_2
    REAL,INTENT(IN)::Y_2
    REAL,INTENT(IN)::SIGMA_SQUARE_T_L
    REAL,INTENT(IN)::L_T_L
    REAL::H
    H=SQRT(((X_1-X_2)**2)+((Y_1-Y_2)**2))
!    GAMMA_H_T_L=SIGMA_SQUARE_T_L*(1-EXP(-((H/L_T_L)**2)))
    GAMMA_H_T_L=SIGMA_SQUARE_T_L-SIGMA_SQUARE_T_L*(1-EXP(-((H/L_T_L)**2)))
    END FUNCTION


    FUNCTION GAMMA_H_L(X_1,Y_1,X_2,Y_2)
    REAL,INTENT(IN)::X_1
    REAL,INTENT(IN)::Y_1
    REAL,INTENT(IN)::X_2
    REAL,INTENT(IN)::Y_2
    REAL::SIGMA_SQUARE_L,L_L,H
    OPEN(UNIT=102,FILE='VARIOGRAM_PARAMETERS_L.TXT',STATUS='OLD')
    READ (102,*) SIGMA_SQUARE_L,L_L
    CLOSE (102)
    H=SQRT(((X_1-X_2)**2)+((Y_1-Y_2)**2))
!    GAMMA_H_L=SIGMA_SQUARE_L*(1-EXP(-((H/L_L)**2)))
    GAMMA_H_L=SIGMA_SQUARE_L-SIGMA_SQUARE_L*(1-EXP(-((H/L_L)**2)))
    END FUNCTION



    SUBROUTINE MATINV(A,N1,B,M1,DETERM,ID)
!C       MATRIX INVERSION
        DIMENSION A(N1,N1),B(N1,1),IN1(N1),IN2(N1),IN3(N1)
        M=M1
        N=N1
  10    DETERM=1.00
  15    DO 20 J=1,N
  20    IN3(J)=0
  30    DO 550 I=1,N
  40    AMAX=0.00
  45    DO 105 J=1,N
        IF(IN3(J)-1)60,105,60
  60    DO 100 K=1,N
        IF(IN3(K)-1)80,100,999
 999    ID=2
        GOTO 740
  80    IF(AMAX-ABS(A(J,K)))85,100,100
  85    IROW=J
  90    ICOLUM=K
        AMAX=ABS(A(J,K))
  100   CONTINUE
  105   CONTINUE
        IN3(ICOLUM)=IN3(ICOLUM)+1
  260   IN1(I)=IROW
  270   IN2(I)=ICOLUM
  130   IF(IROW-ICOLUM)140,310,140
  140   DETERM=-(DETERM)
  150   DO 200 L=1,N
  160   SWAP=A(IROW,L)
  170   A(IROW,L)=A(ICOLUM,L)
  200   A(ICOLUM,L)=SWAP
        IF(M)310,310,210
  210   DO 250 L=1,M
  220   SWAP=B(IROW,L)
  230   B(IROW,L)=B(ICOLUM,L)
  250   B(ICOLUM,L)=SWAP
  310   PIVOT=A(ICOLUM,ICOLUM)
  330   A(ICOLUM,ICOLUM)=1.00
  340   DO 350 L=1,N
  350   A(ICOLUM,L)=A(ICOLUM,L)/PIVOT
  355   IF(M)380,380,360
  360   DO 370 L=1,M
  370   B(ICOLUM,L)=B(ICOLUM,L)/PIVOT
  380   DO 550 L1=1,N
  390   IF(L1-ICOLUM)400,550,400
  400   T=A(L1,ICOLUM)
  420   A(L1,ICOLUM)=0.0
  430   DO 450 L=1,N
  450   A(L1,L)=A(L1,L)-A(ICOLUM,L)*T
  455   IF(M)550,550,460
  460   DO 500 L=1,M
  500   B(L1,L)=B(L1,L)-B(ICOLUM,L)*T
  550   CONTINUE
  600   DO 710 I=1,N
  610   L=N+1-I
  620   IF(IN1(L)-IN2(L))630,710,630
  630   JROW=IN1(L)
  640   JCOLUM=IN2(L)
  650   DO 705 K=1,N
  660   SWAP=A(K,JROW)
  670   A(K,JROW)=A(K,JCOLUM)
  700   A(K,JCOLUM)=SWAP
  705   CONTINUE
  710   CONTINUE
        DO 730 K=1,N
        IF(IN3(K)-1)715,720,715
  715   ID=2
        GO TO 740
  720   CONTINUE
  730   CONTINUE
        ID=1
  740   RETURN

        END
